### PR TITLE
CHB-120 _Create Consumer Authentication

### PR DESCRIPTION
**Pull request by toniastro**

### CODE REVIEW

**Review by ahmadore — COMMENTED** [review]
LGTM,  why the changes on Merchant Table from Json to Text

**Comment by toniastro** [comment]
> LGTM, why the changes on Merchant Table from Json to Text

JSON type would fail on MySql 5.5.* versions; hence why i replaced to text.

**Comment by ndy40** [comment]
What version of mysql is recommended?

**Comment by toniastro** [comment]
> What version of mysql is recommended?

MySql 5.5 up still works okay.

**Pull request merged**
